version: "3.3"
services:
  web:
    build: 
      context: ./booksquire-api
      dockerfile: Development.Dockerfile
    volumes:
      - ./booksquire-api:/app
    ports:
      - "3000:8080"
  app:
    build:
      context: ./booksquire
      dockerfile: Development.Dockerfile
    volumes:
      - ./booksquire:/app
    ports:
      - "3001:3001"
